# DevOps Build Pipeline
# Create and test a Python package on multiple Python versions.
# Chris Joakim, Microsoft, 2020/02/24
# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

# git remote -v
# git remote add devops chjoakim@vs-ssh.visualstudio.com:v3/chjoakim/ggps/ggps
# git remote -v
# devops	chjoakim@vs-ssh.visualstudio.com:v3/chjoakim/ggps/ggps (fetch)
# devops	chjoakim@vs-ssh.visualstudio.com:v3/chjoakim/ggps/ggps (push)
# origin	git@github.com:cjoakim/ggps.git (fetch)
# origin	git@github.com:cjoakim/ggps.git (push)
# git push devops master

trigger:
  - master
  
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  
  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'
  