# DevOps Build & Release Pipeline
# Chris Joakim, Microsoft, 2020/02/24

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: sudo apt-get install python3-venv
  displayName: 'install python3-venv'

- script: python3 --version
  displayName: 'display python3 version (3.5.2)'
  # Python 3.5.2

- script: pip3 --version
  displayName: 'display pip3 version'
  # pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)

- script: pip3 install --upgrade pip3
  displayName: 'pip3 install --upgrade pip3'

- script: pip3 --version
  displayName: 'display pip3 version'

- script: pip3 install -r requirements.txt
  displayName: 'pip3 install -r requirements.txt'

- script: pip3 list
  displayName: 'pip3 list'

- script: ls -alR
  displayName: 'ls -alR'

# - script: source bin/activate
#   displayName: 'source bin/activate'

# - script: rstcheck README.rst 
#   displayName: 'rstcheck README.rst'

- script: pytest -v --cov=ggps/ --cov-report html tests/
  displayName: 'pytest with coverage report'

- script: date -u > build_date.txt
  displayName: 'create build date file'
